# This cloudbuild is run on the creation of new tags, which should signify releases.
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "Dockerfile",
           "-t", "us.gcr.io/grafeas/grafeas-server:$TAG_NAME", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "helm/Dockerfile",
           "-t", "us.gcr.io/grafeas/helm-release:$TAG_NAME", "."]
  - name: "us.gcr.io/grafeas/helm-release:$TAG_NAME"
images: ["gcr.io/grafeas/grafeas-server:$TAG_NAME",
]
