replicaCount: 1

image:
  repository: us.gcr.io/grafeas
  name: grafeas-server
  tag: v0.1.0
  pullPolicy: IfNotPresent

nameOverride: "grafeas-server"
fullnameOverride: "grafeas-server"

# The name of persistent volume to use
# persistent volume is used for storing the embedded grafeas data
persistentVolumeClaimName: "grafeas"

# The type of storage used, supported options: memstore or embedded
# REMARK: embedded storage requires a persistent volume
storageType: "memstore"

service:
  type: ClusterIP
  port: 443

# Certificates for mutual authentication
certificates:
  name: grafeas-ssl-certs
  ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

livenessprobe:
  initialDelaySeconds: 15
  periodSeconds: 20

readinessprobe:
  initialDelaySeconds: 5
  periodSeconds: 10
