replicaCount: 1

image:
  repository: grafeas
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# The name of persistent volume to use
# persistent volume is used for storing the embedded grafeas data
persistentVolumeClaimName: "grafeas"

# The type of storage used, supported options: memstore or embedded
# REMARK: embedded storage requires a persistent volume
storageType: "memstore"

service:
  type: ClusterIP
  port: 443

# Certificates for mutual authentication
certificates:
  name: grafeas-ssl-certs
  ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
  key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----